### PR TITLE
Add options.go to exclusion

### PR DESCRIPTION
**Pull request by xuezhaojun**
Signed-off-by: xuezhaojun <zxue@redhat.com>

https://github.com/stolostron/backlog/issues/22701

### CODE REVIEW

**Comment by xuezhaojun** [comment]
/assing @haoqing0110  It should meet 80%+ coverage after merge.

**Comment by xuezhaojun** [comment]
/hold 
Util release PR merged.

**Review by haoqing0110 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
