### PR TITLE
Trigger 2.2/2.7

### PR DESCRIPTION
**Pull request by xuezhaojun**
Signed-off-by: xuezhaojun <zxue@redhat.com>

### CODE REVIEW

**Comment by haoqing0110** [comment]
can we use this PR to trigger https://github.com/stolostron/clusterlifecycle-state-metrics/pull/93 ?

**Comment by xuezhaojun** [comment]
> can we use this PR to trigger #93 ?

Sure, we can.

**Comment by haoqing0110** [comment]
close as already triggered by https://github.com/stolostron/clusterlifecycle-state-metrics/pull/93

**Pull request closed without merging**
